### ISSUE TITLE
Error in adding prefix

### ISSUE THREAD

**Issue by ruiatelsevier** [stkenny/grefine-rdf-extension#27]
One error happened when I was trying to add prefix 'xsd' which can be detected by 'prefix.cc'. Another error happened when I was trying to add my self-defined prefix. 
<img width="814" alt="Screenshot 2019-06-28 at 13 58 16" src="https://user-images.githubusercontent.com/36567388/60343998-7c945a80-99ad-11e9-9936-ca0d5991af0a.png">
<img width="808" alt="Screenshot 2019-06-28 at 13 57 32" src="https://user-images.githubusercontent.com/36567388/60343999-7c945a80-99ad-11e9-8135-df06a60c7bc2.png">

Any thoughts? Thank you!

**Comment by ktk** [comment]
Like many other prefixes, XSD cannot be properly dereferenced. I don't want to go into details but that is one of the reasons why we created [this repository](https://github.com/zazuko/rdf-vocabularies/), which is sourcing existing ontologies as RDF and "bundles" them.

The API is around node.js/JavaScript but what the RDF-Extension could do is simply use the sourced ontologies (see `ontologies` folder in our repo) instead of fetching them every time. Fetching could still be a fallback for those who are not in our package (we are opinionated, in terms of we do not source everything out there).

By the way behind a proxy we have the same problem for all vocabs, I just recently could not get any vocabs loaded in a scenario where the person working on it was in a corporate network.

**Comment by ktk** [comment]
Ah alternatively we provide a simple API for a lookup service we just released around this, see https://prefix.zazuko.com/api. Not sure if that would be enough though, it's mainly about shrinking and expanding. And it would not solve the proxy issue.

**Comment by ruiatelsevier** [comment]
Thank you so much, @ktk !

**Comment by stkenny** [comment]
In the case of the xsd prefix there is an error trying to parse what is returned from the prefix url.

For the local prefix it is trying to retrieve the vocab from example.org, which won't work. What you can do for this is use the advanced option and upload from a local file instead.

![Screenshot from 2019-06-30 09-59-12](https://user-images.githubusercontent.com/1716730/60394532-d4ea6a00-9b1d-11e9-9ae2-210b60669d1b.png)
